name: Build and Release VoicemeeterBypass

on:
  push:
    tags:
      - v*  # Runs when there's a new tag

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache MSYS2 packages
        uses: actions/cache@v3
        id: cache-msys2
        with:
          path: C:\tools\msys64\var\cache\pacman\pkg
          key: ${{ runner.os }}-msys2-packages-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-msys2-packages-

      - name: Install MSYS2
        if: steps.cache-msys2.outputs.cache-hit != 'true'
        run: |
          choco install msys2 --params "/NoUpdate"

      - name: Update MSYS2 and install MinGW compilers
        if: steps.cache-msys2.outputs.cache-hit != 'true'
        run: |
          # Update MSYS2 package database
          C:\tools\msys64\usr\bin\pacman -Syu --noconfirm
          
          # Install MinGW compilers for both 32-bit and 64-bit
          C:\tools\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-i686-gcc
          C:\tools\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-i686-g++
          C:\tools\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-x86_64-gcc
          C:\tools\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-x86_64-g++
          C:\tools\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-i686-binutils
          C:\tools\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-x86_64-binutils

      - name: Compile Program for 32-bit and 64-bit
        run: |
          ./CompileVoicemeeterBypassInjector.ps1

      - name: Upload compiled files
        uses: actions/upload-artifact@v4
        with:
          name: VoicemeeterBypass
          path: |
            ./VoicemeeterBypassInjector_x86.exe
            ./VoicemeeterBypassInjector_x64.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download compiled files
        uses: actions/download-artifact@v4
        with:
          name: VoicemeeterBypass

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./VoicemeeterBypassInjector_x86.exe
            ./VoicemeeterBypassInjector_x64.exe
          generate_release_notes: true
          draft: false
          prerelease: false