name: Build and Release VoicemeeterBypass

on:
  push:
    tags:
      - v*  # Runs when there's a new tag

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MSYS2
        run: |
          choco install msys2 --params "/NoUpdate"

      - name: Update MSYS2 and install MinGW compilers
        run: |
          # Update MSYS2 package database
          C:\tools\msys64\usr\bin\pacman -Syu --noconfirm
          
          # Install MinGW compilers for both 32-bit and 64-bit
          C:\tools\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-i686-gcc
          C:\tools\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-i686-g++
          C:\tools\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-x86_64-gcc
          C:\tools\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-x86_64-g++
          C:\tools\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-i686-binutils
          C:\tools\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-x86_64-binutils

      - name: Compile Program for 32-bit and 64-bit
        run: |
          ./CompileVoicemeeterBypassInjector.ps1

      - name: Upload compiled files
        uses: actions/upload-artifact@v4
        with:
          name: VoicemeeterBypass
          path: |
            ./VoicemeeterBypassInjector_x86.exe
            ./VoicemeeterBypassInjector_x64.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download compiled files
        uses: actions/download-artifact@v4
        with:
          name: VoicemeeterBypass

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release ${{ github.ref }}"
          body: "Release of VoicemeeterBypass compiled for 32-bit and 64-bit."
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./VoicemeeterBypassInjector_x86.exe
          asset_name: VoicemeeterBypassInjector_x86.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./VoicemeeterBypassInjector_x64.exe
          asset_name: VoicemeeterBypassInjector_x64.exe
          asset_content_type: application/octet-stream