name: Build and Upload VoicemeeterBypass

on:
  push:
    branches:
      - main  # O la rama que prefieras
  pull_request:
    branches:
      - main  # O la rama que prefieras

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Zig
        run: |
          sudo apt-get update
          snap install zig --classic --beta

      - name: Compile with Zig
        run: |
          zig cc -o "./VoicemeeterBypass.exe" "./src/VoicemeeterBypass.c"

      - name: Upload compiled file to repository
        uses: actions/upload-artifact@v3
        with:
          name: VoicemeeterBypass
          path: ./VoicemeeterBypass.exe

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download compiled file
        uses: actions/download-artifact@v3
        with:
          name: VoicemeeterBypass

      - name: Commit and push executable
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./VoicemeeterBypass.exe
          git commit -m "Add compiled VoicemeeterBypass.exe"
          git push origin main  # Asegúrate de que esté empujando a la rama correcta
